### ISSUE TITLE
Map Glitched

### ISSUE THREAD

**Issue by JordonEdits** [Austin-R418/TARP-Bug-Tracker#1]
So when i log on my map is ether out of the circle or it goes full square 

Full Square: https://gyazo.com/020baa8927898330e193169019295d40

I've relogged and also cleared my cache but it still shows up

**Comment by HypnoticSiege** [comment]
Do you press any weird keys when in game. When in game also try and press "Z" to see if that helps at all :)

**Comment by JordonEdits** [comment]
nope i dont and i've tried that nothing happens

**Comment by Austin-R418** [comment]
This is an interesting situation. I have not been able to reproduce this bug on my end. I do have a few questions for you.

1. Does this happen every time you get into the server?
2. When does it start? As soon as you log in? 10 min after you spawn?
3. When you are in game and it happens can you please press F8 and see if there are any errors in there.

**Comment by JordonEdits** [comment]
1. yes it's every time its either the full square or the map out of the circle as I will leave below (https://gyazo.com/367f0e99bc2d4cfe2e24f6801419f6b8)
2. it starts when I'm in the game.
3. i don't see any errors

**Comment by Austin-R418** [comment]
Alright I’ll see what we can get together to try and get it fixed for you.

**Comment by Austin-R418** [comment]
Note: Possible conflicting scripts causing the issue.

**Comment by JordonEdits** [comment]
maybe but hopefully we can fix it

**Comment by Austin-R418** [comment]
I just pushed a possible fix for this issue. After the next restart if it is still broken let me know.

**Comment by JordonEdits** [comment]
i've just looked and also cleared my cache and it is still doing it

**Comment by ItsTheSneakyTurtle** [comment]
It has happened to me a few times and I've noticed it mostly when I either switch character or if there has been a game crash and I don't close the FiveM application. I've not seen it in the past couple of days, however.

**Comment by JordonEdits** [comment]
yeah it seems to happen to me all the time as soon as I open FiveM and load into the character selection it starts

**Comment by Austin-R418** [comment]
Is this still an issue? If it is can you please confirm for me that you have:
- Cleared your cache
- Do not have any client side scripts installed in your FiveM Folder.

If you have taken these steps once I return I will reach out to you personally to help get this issue fixed.

**Comment by JordonEdits** [comment]
yeah i have cleared my cash and I don't belive so that I have any client side scripts in my fivem folder

**Comment by JordonEdits** [comment]
only scripts i have is what i have received from the server

**Comment by JordonEdits** [comment]
got it fixed i had the safe zone bar to high
