### ISSUE TITLE
Screen is still black and white after being revived by local doctor

### ISSUE THREAD

**Issue by Addoie** [Austin-R418/TARP-Bug-Tracker#11]
**Describe the bug**
For about 5 minutes after you are revived by the local doctor after being unconcious your screen stays black and white.

**To Reproduce**
1. Gety knocked out by your mate
2. get your mate to drop you at the local doctor
3. press E to be healed.

**Expected behavior**
You should be revived and screen should return to normal.

**Screenshots**
https://imgur.com/a/BHAUqJB

**Additional context**
N/A

**Comment by theblitz1738** [comment]
@Fitzie1414 If it helps any, this occurred to me as well. I was knocked unconscious and was taken to the doctor to be treated. I had to be treated by the doctor three times over a period of 15 minutes for normal color to return.

**Comment by Fitzie1414** [comment]
I'm thinking I just need to either fix or add the section to remove that screen effect. I still need to dig into the script, but should be a fairly simple fix (famous last words there)

**Comment by Austin-R418** [comment]
Issue resolved
