### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by RonRuncles** [Austin-R418/TARP-Bug-Tracker#13]
![image](https://user-images.githubusercontent.com/85252965/121791343-84576480-cbae-11eb-9f40-d9cab1f23153.png)

While trying to join the server, this is the message i am getting.. I have restarted fivem several times and it keeps giving me this message.

**Comment by HypnoticSiege** [comment]
FiveM is currently having issues. This is not just our Sever, but a couple other servers. Please wait for FiveM to fix this and you should be good! Nothing we can do on Back End. 
Sorry!
