### ISSUE TITLE
Garbage Job Broken

### ISSUE THREAD

**Issue by Zacrate** [Austin-R418/TARP-Bug-Tracker#14]
**Describe the bug**
When having the Garbage Man selected as your job it doesn't bring up any spots on the map to go to for work or a vehicle. I am unsure if there is a menu I am Unfamiliar with or it is bugged so I am submitting this report.

**To Reproduce**
1. Go to Information center for a job
2. Click on Garbage to select job

**Expected behavior**
There should be a prompt or follow up to allow people to do the job - Or is it roleplay dependent

**Screenshots**

**Additional context**
Once again I am unsure if this job is more of a role play job or an actual job with steps and processes. Feel free to message me on Discord to provide any additional info that I may not be aware of, lots of Love - Dave Snyder

**Comment by MyLifeAsRK3** [comment]
Fix going in with the next update.
