### ISSUE TITLE
Players Invisible 

### ISSUE THREAD

**Issue by SaltyEclipse** [Austin-R418/TARP-Bug-Tracker#16]
**Describe the bug**
Paul A, and I (John L.) have gotten an issue with the server where we can't see other players except ourselves. I can't see him or can't see anyone else. When I changed characters it fixed it but when I switch back  it doesn't work. 

**To Reproduce**
Can't seem to figure out how it happened.

**Expected behavior**
I should be able to see all other players.

**Screenshots**

**Additional context**
It happened one day when we both got on and it happened to us.

**Comment by Fitzie1414** [comment]
Unable to replicate
