### ISSUE TITLE
When unconcious the downed individual cannot communicate with anyone who is concious.

### ISSUE THREAD

**Issue by Addoie** [Austin-R418/TARP-Bug-Tracker#17]
**Describe the bug**
When an individual is unconcious they can hear everything the people within range of their voicebox say but when they try and respond they cannot be heard by the concious players.

**To Reproduce**
1. Knock someone unconcious (with permission obviously)
2. ask them to speak
3. See error

**Expected behavior**
The unconcious person should be able to communicate wth those people in range of their voicebox.

**Screenshots**
N/A cannot be represented in a screenshot.

**Additional context**
That's all

**Comment by Austin-R418** [comment]
This is not a bug, this is a feature. When someone is unconscious they are not able to speak IRL so they will not be a belt o speak in game.

**Comment by Addoie** [comment]
> This is not a bug, this is a feature. When someone is unconscious they are not able to speak IRL so they will not be a belt o speak in game until they are resuscitated.

But this makes it so EMS doesn’t know how long the patient has left. And they can’t communicate and tell us how long they have left. Would it be possible to incorporate into the medical menu a timer so ems knows how long they have before they force respawn?

**Comment by ItsTheSneakyTurtle** [comment]
> > This is not a bug, this is a feature. When someone is unconscious they are not able to speak IRL so they will not be a belt o speak in game until they are resuscitated.
> 
> But this makes it so EMS doesn’t know how long the patient has left. And they can’t communicate and tell us how long they have left. Would it be possible to incorporate into the medical menu a timer so ems knows how long they have before they force respawn?

Talk in the /gooc chat and let them know if you are about to bleed out.
