### ISSUE TITLE
Bodybag makes players invisible

### ISSUE THREAD

**Issue by Addoie** [Austin-R418/TARP-Bug-Tracker#18]
**Describe the bug**
If you bodybag an unconcious individual through the medical menu, the person who is being bodybagged can see they are in a bodybag but for anyone else the bodybagged individual becomes invisible.

**To Reproduce**
1. Knock someone unconcious (with permission of course)
2. Bodybag them
3. See error

**Expected behavior**
You can see a bodybag laying on the ground.

**Screenshots**
N/A cannot be represented in a screenshot.

**Additional context**
That's all.

**Comment by Austin-R418** [comment]
Issue resolved
