### ISSUE TITLE
Not being able to stack things in the inventory  

### ISSUE THREAD

**Issue by cman225** [Austin-R418/TARP-Bug-Tracker#2]
We can not stack things in the inventory like poppy's and weed and things without pictures. But things with pictures like money that have pictures we can stack.

**Comment by Austin-R418** [comment]
Thank you for submitting a bug report. We have looked into this issue and have found the solution. Expect a fix to be released soon!

**Comment by Austin-R418** [comment]
Bug fixed. On next update the issue will be resolved.
