### ISSUE TITLE
Medical script

### ISSUE THREAD

**Issue by MADDHATTR3SS** [Austin-R418/TARP-Bug-Tracker#22]
**Describe the bug**
Medical script seems to have a bug where you can wait out your timer and spam F10 and it lets you stand up and walk away. Also noticed that you respawn where you go down. This created a huge issue in which a person was supposed to be under new life rule and respawn out of a situation however because of the bug they were in the same place and RP continued which they deemed unfair. 

**To Reproduce**
1. Get killed
2. Wait out the timer
3. Spam f10
4. Walk away like nothing happened
5. Zach has tested this bug with me and hammer and it is definitely an issue

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by Austin-R418** [comment]
Issue Resolved
