### ISSUE TITLE
Item drop

### ISSUE THREAD

**Issue by MADDHATTR3SS** [Austin-R418/TARP-Bug-Tracker#23]
**Describe the bug**
There is a bug in certain buildings like banks, if you drop something on the floor there it can not be picked up. Had someone drop 100k on the ground for his friend and it could not be picked up, won’t even let you enter the inventory menu. Tested it last night Jefe dropped a bunch of stuff on the floor and no one was able to pick it up in Fleeca bank in legion square.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by MyLifeAsRK3** [comment]
Tested this in the dev server and it wasn't an issue, will test in main server and see if the issue persists.

**Comment by MyLifeAsRK3** [comment]
This works in the main server, perhaps server restart fixed it.  Closing bug.
