### ISSUE TITLE
Missing Ammunition

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Bug-Tracker#26]
Since the implementation of V.2x(whatever it is now), the ammunition for the Marksman Rifle is missing from the police armory. It was previously labeled as "7.62 NATO". Additionally, the ammo did not have a picture associated with it.

**To Reproduce**
1. Go to Police Armory
2. Go to chevron to open armory
3. Click 'e' to open armory
4. The content of the armory does not contain ammo suitable for Marksman Rifle.

![20210628030919_1](https://user-images.githubusercontent.com/85204661/123602623-91836e80-d7be-11eb-81ce-132a1a111e06.jpg)

**Comment by Austin-R418** [comment]
Issue resolved
