### ISSUE TITLE
Prison Issues

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Bug-Tracker#27]
There are various parts of this bug so I will attempt to describe them all in one explanation then in a step-by-step mode.

I had a person jail me for a period of time for testing this. When I was sent to jail, I lost my current clothing. I turned into a female character wearing a bikini swimsuit and a police duty belt - this was the clothing for the remainder of my jail time (screenshot included). When I was released from my sentence, by the script, however I returned to the world with my player but no clothing, boxers only. After speak with several frequent inmates, they advised that only sometimes this happens. I tested it two or three times and it happened every time to me.

While in prison, I went to the area to visit a friend. While my friend was there we were able to pass items back and forth between one another. So hypothetically, you could obtain a weapon from my friend and return to the prison area and kill other prisoners. Another part of this that ties to the next part in the next paragraph is that you on the public side are able to use the '/carry' command and carry your friend out of the prison. However, at the end of their sentence they teleport back.

While going back and forth between the different areas, I was able to go visit the "security area" which is the public side of the prison and I was able to go to the exit door and leave the prison. After leaving the prison, the interior door opened and I was able to walk around the normal base GTA V interior but the walls and such did not exist and I was able to go anywhere (video included). However, at the end of the prison sentence you get teleported back to the front doors of Bolingbroke. 
**This bug also works vice versa - the prisoner can leave the prison and the public can come in the secured area of the prison.**

To Reproduce Leaving Jail:
1. While in jail, go to jail doors
2. Click 'e' to open menu, select 'security'
3. Once teleported to the public jail visitation side, click 'e' to open menu again
4. While in the menu, select the 

**Expected behavior**
1. For clothing, I'd expect some sort of orange jumpsuit or the players normal clothing. Then when released to get your clothing back.
2. I'd expect you not to be able to give/receive items while in the visitation area because it's separated by glass.
3. I'd except you not to be able to 'leave' or escape the prison and not be able to go to the public visitation side either

**Screenshots**
![20210628040216_1](https://user-images.githubusercontent.com/85204661/123612050-d1028880-d7c7-11eb-9220-44d1cf7d9228.jpg)

https://youtu.be/3HENHyhFITM - This video shows the clothing error, visiting and transferring items, and leaving the prison
https://youtu.be/xe3RcwwgeUE - This video shows the wall error.

**Comment by Fitzie1414** [comment]
Problem solved.

Security no longer appears as an option for prisoners leaving the jail area.
Jail no longer appears as an option for visitors.

Jumpsuits now apply properly for male & female peds.

Walls issue will be resolved in the future with possible new prison interior.
