### ISSUE TITLE
Medical script

### ISSUE THREAD

**Issue by MADDHATTR3SS** [Austin-R418/TARP-Bug-Tracker#28]
**Describe the bug**
medical script stopped working last night after restart. X menu does not pull up the body diagram menu at all, can’t not fix wounds. 

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by theblitz1738** [comment]
Issue resolved - tested and now working.

**Comment by theblitz1738** [comment]
Ticket reopened as medical menu is not working as of 06/30/21 at 1142 EST.

**Comment by Austin-R418** [comment]
Issue resolved
