### ISSUE TITLE
Banking Translation Errors

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Bug-Tracker#30]
**Describe the bug**
When depositing, withdrawing, or transferring money the notification is not translated to English. The screenshot provided is from a deposit, but it also exists when depositing and withdrawing from any ATM or Bank location. The error also occurs when transferring money via the phone app.

**To Reproduce**
1. Go to Bank or ATM
2. Withdraw or Deposit Money
3. See error

**Expected behavior**
The notification should be translated into English.

**Screenshots**
![20210629085534_1](https://user-images.githubusercontent.com/85204661/123811169-9e848880-d8b8-11eb-8e5d-947dd9897957.jpg)

**Comment by MyLifeAsRK3** [comment]
This has been completed in development and will be moved to the main server this evening.  Thank you!
