### ISSUE TITLE
Police Vehicle Issues

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Bug-Tracker#35]
There are three issues:
1. The police vehicle shop lists the model names of the vehicles as sahp1, sahp2, sahp3, etc.
2. The Dodge Challenger police vehicle still is listed as NULL in the garage
3. The siren script has the base game sirens and not the custom sirens previously in the menu.

**To Reproduce**
1. Go to police vehicle spawn location
2. Click on vehicle shop

**Expected behavior**
1/2 - the police garage script updated so the model names show in the shop and the model name appears in the garage
3 - replace or fix the siren script to have the other sirens listed in the options.

**Comment by Fitzie1414** [comment]
It sounds like some files may not have copied properly. Will need someone with live server access to verify the spfleet vehicles.meta and the lux_vehcontrol SIRENS.lua

**Comment by Fitzie1414** [comment]
Sirens and Vehicle shop fixed.

Still getting reports of issues with the vehicle garage

**Comment by Fitzie1414** [comment]
Fixed
