### ISSUE TITLE
Disappearing Handcuffs

### ISSUE THREAD

**Issue by theblitz1738** [Austin-R418/TARP-Bug-Tracker#38]
**Describe the bug**
After arresting someone the handcuffs disappear after 10 minutes. After 10 mins, they disappear and the subject is no longer handcuffed. If they are in the back of a police vehicle they can open the door freely and exit or jump out. 

**To Reproduce**
1. Go on duty
2. Handcuff someone
3. Wait 10 minutes

**Expected behavior**
The handcuffs shouldn't disappear or expire for a longer period of time.

**Comment by Fitzie1414** [comment]
Increased timer to 15 minutes on dev server. Will need to test

**Comment by Fitzie1414** [comment]
Resolving Issue. If there are any further problems, please open another ticket.
