### ISSUE TITLE
Vehicle issue

### ISSUE THREAD

**Issue by RonRuncles** [Austin-R418/TARP-Bug-Tracker#4]
![image](https://user-images.githubusercontent.com/85252965/120534719-c6f79080-c3a7-11eb-9e7b-d5fe70fa2a49.png)

I am unable to see my speed, I'm not able to use my blinkers or hazards, nor am I able to use my seatbelt.

**Comment by Austin-R418** [comment]
Dev Note: ensure trew_hur

**Comment by Austin-R418** [comment]
Issue should be fixed.
