### ISSUE TITLE
Tattoos are bugged again 

### ISSUE THREAD

**Issue by JordonEdits** [Austin-R418/TARP-Bug-Tracker#41]
I went to the tattoo shop bought them and when I'm on the menu to buy them I can see them but as soon as I come out of the menu they disappear I will leave screenshots below.

In the menu to buy them: https://gyazo.com/f7676094d0a862574f8dae254b88d1

Out of the Menu: https://gyazo.com/9f4e0f0759ee3decb8ca17c76711f777

**Comment by Austin-R418** [comment]
Issue resolved
