### ISSUE TITLE
Police Garage in Mt Chilliad?

### ISSUE THREAD

**Issue by ItsTheSneakyTurtle** [Austin-R418/TARP-Bug-Tracker#43]
**Describe the bug**
The Police garage is a bit far away from where I believe it should be.

**To Reproduce**
Nothing to reproduce

**Expected behavior**
It is expected to be at Paleto Sheriff's Office, I think?

**Screenshots**
https://media.discordapp.net/attachments/837740816940138617/862088753950490624/unknown.png

**Additional context**
Uh none.

**Comment by Austin-R418** [comment]
Issue resolved
