### ISSUE TITLE
Unable to drink water

### ISSUE THREAD

**Issue by Addoie** [Austin-R418/TARP-Bug-Tracker#44]
**Describe the bug**
When users attempt to drink water they cannot.

**To Reproduce**
1. Get water
2. Open Inventory
3. Drag it to use or put it in a hotbar slot and attempt to use it

**Expected behavior**
You should drink the water.

**Screenshots**
https://imgur.com/a/ERtFGaN

**Additional context**
Eating food works it is just water that doesn't

**Comment by Austin-R418** [comment]
Issue resolved
