### ISSUE TITLE
Vehicle upgrades

### ISSUE THREAD

**Issue by Banjo1111** [Austin-R418/TARP-Bug-Tracker#47]
**Describe the bug**
Upgrading a vehicle charges you twice for 1 upgrade.

**To Reproduce**
1. Go to vehicle mod shop
2. go to upgrades
3. purchase an upgrade ex. Engine level 1
**Expected behavior**
Should have only charged me once

**Screenshots**
N/a
**Additional context**
N/a

**Comment by Fitzie1414** [comment]
Fixed this issue.

New script for police vehicle editing was still using the same server calls. Changed calls so they wouldn't overlap. Both shops now only charge once for each mod.
