### ISSUE TITLE
seatbelt

### ISSUE THREAD

**Issue by brookins2013** [Austin-R418/TARP-Bug-Tracker#5]
**Describe the bug**

There is no way to use the seat belt now and there are no key binds for it on the server. page up no longer operates the seat belt and it does not work on the controller either.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected/should have happened.

**Screenshots**

**Additional context**

**Comment by Austin-R418** [comment]
Issue should be fixed. Set your keybind in your GTA settings.
